[project]
name = "bau-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "torch>=2.7.0",
    "transformer-lens>=2.15.4",
]
